# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('page_count', models.IntegerField()),
                ('ISBN_10', models.CharField(max_length=13)),
                ('pic_url', models.CharField(max_length=200)),
            ],
        ),
    ]
