# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190111_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
