# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190111_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic_url', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN_10',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[(None, 'Other'), ('Evangelism & Missions', 'Evangelism & Missions'), ('Commentaries & Reference', 'Commentaries & Reference'), ('Church Ministry', 'Church Ministry'), ('Arts & Literature', 'Arts & Literature'), ('Academic', 'Academic'), ('Theology', 'Theology'), ('Christian Living', 'Christian Living'), ('Apologetics', 'Apologetics'), ('Bible Studies & Devotionals', 'Bible Studies & Devotionals'), ('Biblical Studies', 'Biblical Studies'), ('Education', 'Education')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
